services:
  webapi:
    build:
      context: .
      dockerfile: ./Dockerfile       
    # environment:
    #   SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

    

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    # volumes:
    #   - db_data:/var/opt/mssql
