global:
  scrape_interval: 15s

scrape_configs:
  - job_name: aspnet_api
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5000']   # Windows host - containers

  - job_name: mssql
    static_configs:
      - targets: ['mssql-exporter:4000']
